version: 2.0

references:
  # Environment variables
  #
  WP_CORE_DIR: &WP_CORE_DIR
    /tmp/wordpress
  WP_HOST: &WP_HOST
    passwords-evolved.test
  WP_ORG_PLUGIN_NAME: &WP_ORG_PLUGIN_NAME
    passwords-evolved
  WP_ORG_USERNAME: &WP_ORG_USERNAME
    carlalexander

  # Default container configuration
  #
  container_config: &container_config
    docker:
      - image: circleci/php:7.3
    environment:
      - WP_CORE_DIR: *WP_CORE_DIR
      - WP_HOST: *WP_HOST
      - WP_ORG_PLUGIN_NAME: *WP_ORG_PLUGIN_NAME
      - WP_ORG_USERNAME: *WP_ORG_USERNAME
    working_directory: ~/passwords-evolved

  workspace_root: &workspace_root
    /tmp

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  copy_vendor: &copy_vendor
    run:
      name: Copy vendor directory
      command: cp -R /tmp/vendor .

  install_subversion: &install_subversion
    run:
      name: Install subversion
      command: sudo apt-get install subversion

  run_phpunit: &run_phpunit
    run:
      name: Run PHP unit tests
      command: vendor/bin/phpunit --verbose

  update_packages: &update_packages
    run:
      name: Update packages
      command: sudo apt-get update

  # Default configuration for all behat testing jobs
  #
  behat_job: &behat_job
    <<: *container_config
    docker:
      - image: circleci/php:7.3
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - run:
          name: Add WordPress host to hosts file
          command: echo "127.0.0.1 ${WP_HOST}" | sudo tee -a /etc/hosts
      - *attach_workspace
      - *copy_vendor
      - *update_packages
      - run:
          name: Install MySQL client
          command: sudo apt-get install default-mysql-client
      - run:
          name: Install MySQL PHP extension
          command: sudo docker-php-ext-install mysqli
      - run:
          name: Setup WordPress
          command: .circleci/setup-$WP_TYPE.sh
      - run:
          name: Start PHP server
          command: sudo php -S $WP_HOST:80 -t $WP_CORE_DIR
          background: True
      - run:
          name: Run Behat tests
          command: vendor/bin/behat --config .circleci/behat.yml --format progress --tags=$WP_TYPE

  # Default configuration for all phpunit testing jobs
  #
  phpunit_job: &phpunit_job
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *copy_vendor
      - *run_phpunit

  # Configuration for phpunit testing jobs that require libsodium. Only necessary before PHP 7.2.
  #
  libsodium_phpunit_job: &libsodium_phpunit_job
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *copy_vendor
      - *update_packages
      - run:
          name: Install libsodium
          command: sudo apt-get install libsodium-dev
      - run:
          name: Install libsodium PHP extension
          command: sudo pecl install -f libsodium
      - run:
          name: Activate libsodium extension
          command: sudo docker-php-ext-enable sodium
      - *run_phpunit

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: composer install -n -o
      - run:
          name: Install WordPress
          command: bash .circleci/install-wp.sh
      - persist_to_workspace:
          root: .
          paths:
            - vendor
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - wordpress

  code_quality:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *copy_vendor
      - run:
          name: Run code quality tests
          command: vendor/bin/grumphp run --testsuite=code_quality

  test_php74:
    <<: *phpunit_job
    docker:
      - image: circleci/php:7.4

  test_php73:
    <<: *phpunit_job
    docker:
      - image: circleci/php:7.3

  test_php72:
    <<: *phpunit_job
    docker:
      - image: circleci/php:7.2

  test_php71_libsodium:
    <<: *libsodium_phpunit_job
    docker:
      - image: circleci/php:7.1

  test_php71:
    <<: *phpunit_job
    docker:
      - image: circleci/php:7.1

  test_php70_libsodium:
    <<: *libsodium_phpunit_job
    docker:
      - image: circleci/php:7.0

  test_php70:
    <<: *phpunit_job
    docker:
      - image: circleci/php:7.0

  test_php56_libsodium:
    <<: *container_config
    docker:
      - image: circleci/php:5.6
    steps:
      - checkout
      - *attach_workspace
      - *copy_vendor
      - run:
          name: Update packages
          command: sudo apt-get update
      - run:
          name: Install libsodium
          command: sudo apt-get install libsodium-dev
      - run:
          name: Install libsodium PHP extension
          command: sudo pecl install -f libsodium-1.0.6
      - run:
          name: Activate libsodium extension
          command: sudo docker-php-ext-enable libsodium
      - *run_phpunit

  test_php56:
    <<: *phpunit_job
    docker:
      - image: circleci/php:5.6

  acceptance_singlesite:
    <<: *behat_job
    environment:
      - WP_CORE_DIR: *WP_CORE_DIR
      - WP_HOST: *WP_HOST
      - WP_ORG_PLUGIN_NAME: *WP_ORG_PLUGIN_NAME
      - WP_ORG_USERNAME: *WP_ORG_USERNAME
      - WP_TYPE: singlesite

  acceptance_multisite:
    <<: *behat_job
    environment:
      - WP_CORE_DIR: *WP_CORE_DIR
      - WP_HOST: *WP_HOST
      - WP_ORG_PLUGIN_NAME: *WP_ORG_PLUGIN_NAME
      - WP_ORG_USERNAME: *WP_ORG_USERNAME
      - WP_TYPE: multisite

  acceptance_muplugins:
    <<: *behat_job
    environment:
      - WP_CORE_DIR: *WP_CORE_DIR
      - WP_HOST: *WP_HOST
      - WP_ORG_PLUGIN_NAME: *WP_ORG_PLUGIN_NAME
      - WP_ORG_USERNAME: *WP_ORG_USERNAME
      - WP_TYPE: muplugins

  deploy_assets:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *update_packages
      - *install_subversion
      - run:
          name: Deploy assets to WordPress plugin directory
          command: .circleci/deploy-assets.sh

  deploy_plugin:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *update_packages
      - *install_subversion
      - run:
          name: Deploy new version to WordPress plugin directory
          command: .circleci/deploy-plugin.sh

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy_assets:
          filters:
            branches:
              only:
                - master
      - code_quality:
          requires:
            - build
      - test_php74:
          requires:
            - code_quality
      - test_php73:
          requires:
            - code_quality
      - test_php72:
          requires:
            - code_quality
      - test_php71_libsodium:
          requires:
            - code_quality
      - test_php71:
          requires:
            - code_quality
      - test_php70_libsodium:
          requires:
            - code_quality
      - test_php70:
          requires:
            - code_quality
      - test_php56_libsodium:
          requires:
            - code_quality
      - test_php56:
          requires:
            - code_quality
      - acceptance_singlesite:
          requires:
            - test_php74
            - test_php73
            - test_php72
            - test_php71_libsodium
            - test_php71
            - test_php70_libsodium
            - test_php70
            - test_php56_libsodium
            - test_php56
      - acceptance_multisite:
          requires:
            - test_php74
            - test_php73
            - test_php72
            - test_php71_libsodium
            - test_php71
            - test_php70_libsodium
            - test_php70
            - test_php56_libsodium
            - test_php56
      - acceptance_muplugins:
          requires:
            - test_php74
            - test_php73
            - test_php72
            - test_php71_libsodium
            - test_php71
            - test_php70_libsodium
            - test_php70
            - test_php56_libsodium
            - test_php56
      - deploy_plugin:
          filters:
            branches:
              only:
                - master
          requires:
            - acceptance_singlesite
            - acceptance_multisite
            - acceptance_muplugins
